// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdPPecO0UIlItE-mgSkbMChi3gteaQvwk',
    appId: '1:669640742853:web:30d7b48e027f33188d9dac',
    messagingSenderId: '669640742853',
    projectId: 'kudoswareflutter',
    authDomain: 'kudoswareflutter.firebaseapp.com',
    storageBucket: 'kudoswareflutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiHbDc7RimNoGLVLTo4Ejj9WkGG9XtgdQ',
    appId: '1:669640742853:android:35f153e46c55b7878d9dac',
    messagingSenderId: '669640742853',
    projectId: 'kudoswareflutter',
    storageBucket: 'kudoswareflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApK83nWA5CPWkzQCxfpYqq1ohyyrN2sws',
    appId: '1:669640742853:ios:de8b41d8beec574b8d9dac',
    messagingSenderId: '669640742853',
    projectId: 'kudoswareflutter',
    storageBucket: 'kudoswareflutter.appspot.com',
    iosBundleId: 'com.example.kudoswareFirebase',
  );
}
